[workspace]
members = [
    "texturesofspiderman",
    "SpiderTex",
    "SpiderTexGUI",
    "format-experiment",
    "tracing-egui-repaint",
    "tracing-oncecell",
    "tracing-messagevec",
    "dxgi-format",
]
resolver = "2"
